### ISSUE TITLE
Issue with Xcode 13.2

### ISSUE THREAD

**Issue by suckerSlayer** [SolaWing/xcode-build-server#10]
Recently I upgrade to Xcode13.2, jumping to definition works well with Xcode 12, while in the same project within Xcode13.2 it will fail with a "Definition not found" error in some case. Don't know what changes in sourcekit-lsp and build system whithin it cause this...

**Comment by SolaWing** [comment]
Do you have a reproduce minimum demo? will Clean Cache fixes this problem?

**Comment by suckerSlayer** [comment]
> Do you have a reproduce minimum demo? will Clean Cache fixes this problem?

Will let you know when I finish the minimum demo. By the way, what Xcode version are you using currently? And I use the built-in sourcekit-lsp come with Xcode.

**Comment by SolaWing** [comment]
@suckerSlayer I am use newest 13.2.1, with built in  sourcekit.

**Comment by suckerSlayer** [comment]
@SolaWing It seem to be the lagging problem caused by sourcekit-lsp itself, it just works a little bit unstably. And believe that your log parse it's correct and shouldn't be responsible for it. It happens usually when it comes with functions from an extension within another module, maybe it's too complex to index? I don't know. Now I am wondering if this could be related to my editor environment setting, curious about what environment are you working in, I am use vim from iterm with 'vim-lsp' integrated

**Comment by SolaWing** [comment]
@suckerSlayer I am use vim with coc, cross module goto definition is ok(xcode should build it to refresh indexstore).

**Comment by suckerSlayer** [comment]
@SolaWing I know I always refresh indexstore by Xcode compile, and basically it works fine, maybe I'll try COC later.I will close this issue since it's not Xcode Build Server's problem, thank!
