### ISSUE TITLE
Jump to definition of modules like SwiftUI

### ISSUE THREAD

**Issue by tami5** [SolaWing/xcode-build-server#11]
Hey @SolaWing , I wonder if this can be fixed somehow or is it strictly an Xcode IDE thing..

Basically, sometimes I find it helpful to jump to protocols like View and understand it bit. On Xcode, this just works. 

Thanks

**Comment by SolaWing** [comment]
@tami5 this is impossible, sourcekit provide api to open a module generated interface, and can jump to it. but sourcekit-lsp haven’t yet implemented it. maybe a sourcekit-lsp patch can implement this

**Comment by tami5** [comment]
That's odd, feature exists but isn't accessible. Well patching seems a viable solution, but perhaps not worth it. Sad we can't open an issue on sourcekit-lsp repo, 

Thanks @SolaWing
