### ISSUE TITLE
Discussion: Possible to implement _inside_ an iOS / macOS application?

### ISSUE THREAD

**Issue by tikimcfee** [SolaWing/xcode-build-server#13]
As suggested! I see you've managed to get the lib executing outside it's normal environment. Might be a long shot, but I'm curious if you've experimented with _bundling the LSP_ with another project, for runtime-execution. Use case being I could open my app with this implementation, run a file through it, and execute LSP requests on it.

I think this may essentially require a JIT in the runtime since it may require a full compilation pass, but hey, figured I'd ask.

Thank you so much for posting this information, and sharing your hard work!

**Comment by SolaWing** [comment]
this project is just aim to hook sourcekit-lsp to provide xcode compile information. if you want to use the lsp as runtime api,even run on ios, you can try read lsp source code and compile it and it’s dependency as a lib. this may not easy

**Comment by tikimcfee** [comment]
Thank you much for the heads up! That's exactly what I'm going to try to do, and holy crap does it start to get complicated. I'm looking for other options here as well, so maybe I'll ping later if I find anything else out there to try.
