### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by smolck** [SolaWing/xcode-build-server#14]
Hello! This is a nice and useful project, but currently there is no license information/file anywhere that I can find, which means [the work is under exclusive copyright by default](https://choosealicense.com/no-permission/). If this is intended, no worries, but if not, could information about the license of this project be specified/added somewhere (perhaps in the form of a LICENSE file/similar)?

Thanks!

**Comment by SolaWing** [comment]
Thank you for suggest. I just add a MIT LICENSE
