### ISSUE TITLE
Sample project?

### ISSUE THREAD

**Issue by konrad1977** [SolaWing/xcode-build-server#23]
I cannot get it working. Can you setup a sample project to get it working? I am using Emacs (still need an xcworkspace though but I am building using xcodebuild with parsed information from xcworkspace/xcodeproj), I need to pass any argument to source kit-lsp or (target|sdk)?.

I can get the basics of swiftui and foundation completions but not from my own code. 
Earlier I used the trick with a package.swift in the root to fool sourcekit-lsp but it doesn't seem to work with xcode15.

**Comment by konrad1977** [comment]
I got it working after I compiled using xcodebuild ... | xcode-build-server parse

**Comment by SolaWing** [comment]
I want to know what steps you have taken and what difficulties you have encountered, and it doesn't work in the end. This may help me improve the usage guide.

**Comment by konrad1977** [comment]
I got it working, but do you need to **_clean_** the build every time before you updating the` .compile` commands?

Is it possible to do the parsing from files (I mean from files generated by xcodebuild) and not the output from xcodebuild?

**Comment by SolaWing** [comment]
You could use xcode-build-server parse -a to only overwrite new item, keep old item untouched. if you build use xcode app, it can choose all log, and export to a file.

For generate command from any of the files, can you enlighten me how to get the build flags?

**Comment by konrad1977** [comment]
I am planning to do this automatically using Emacs. So I always have an up to date version of `.compile` commands.

**Comment by konrad1977** [comment]
So If I understand you correctly if you pass `xcodebuild [...] | xcode-build-server parse -a` it will apply the changes needed to update lisp-server if you changed any file?

**Comment by SolaWing** [comment]
> So If I understand you correctly if you pass `xcodebuild [...] | xcode-build-server parse -a` it will apply the changes needed to update lsp-server if you changed any file?

yes.
