### ISSUE TITLE
Monitoring changes and transparency/echo mode

### ISSUE THREAD

**Issue by konrad1977** [SolaWing/xcode-build-server#24]
First of all, this is my life saver for continue using Emacs, thanks!

1. I usually automate my builds in Emacs and parses the warnings/errors directly from the output from Xcodebuild. I would love to have a transparency/echo mode from `xcode-build-server parse` that just echoes back everything from xcodebuild so I can continue to do both parsing while I am compiling and updating the BSP .compile file.

- For echoing back xcodebuild's output yet another flag like `-quiet` would be nice, then you just get the warnings, notes and errors. An easy start is just to return outputs that starts with a path and if the compilation for successful or not.

2. Would be nice to have a tool that detect changes in the rootfolder and subfolders and automatically runs an Xcodebuild and updates the indices for BSP. So we get some kind of background indexing. I think this is possible within emacs, but it would be nice to have for every user not just emacs users.

**Comment by SolaWing** [comment]
I'm glad this project was useful to you. For your question, [yaroslavyaroslav](https://github.com/yaroslavyaroslav) has the same idea as you, see #21 and #22.

For your first need, Although it is convenient to have the -transparency or -quiet option, currently it can be achive by shell, eg:
`xcodebuild ... | tee build.log; xcode-build-server parse build.log 1>/dev/null 2>&1`.

**Comment by konrad1977** [comment]
Ah I see, I must try to integrate this then. Thanks.

**Comment by konrad1977** [comment]
Nice, but it doesn't detect changes in the folder right now and recompiles the project right?

**Comment by SolaWing** [comment]
if you mixed xcode build from ui, and xcodebuild from cli, the build cache maybe invalidate and recompile your code.
