### ISSUE TITLE
No symbols from xcframework

### ISSUE THREAD

**Issue by konrad1977** [SolaWing/xcode-build-server#25]
We have a shared xcframework but I get no auto completion from that.

**Comment by SolaWing** [comment]
does it work in xcode？does .compile file record same flags as xcode build log output？

if possible，can you provide a minimum reproducible project?

**Comment by konrad1977** [comment]
I Found out that this was an emacs issue. For some reason Eglot thinks that the project root is up one level. Just moving the files up worked.
