### ISSUE TITLE
LSP root?

### ISSUE THREAD

**Issue by schwjustin** [SolaWing/xcode-build-server#28]
Hi, I cloned the repo, ran the ln -s command, and then the config command. I got the `Requested but did not find extension point with identifier Xcode` error when running the config command but it seemed to work successfully because a buildServer.json file was created at the root of my project directory. I rebuilt in Xcode, restarted VSCode (I use a VSCode fork called Cursor), and Swift autocomplete doesn't seem to be working.

<img width="248" alt="Screenshot 2023-11-06 at 10 25 01 AM" src="https://github.com/SolaWing/xcode-build-server/assets/18671480/c76b1e76-5d68-448a-95a9-189f340b7465">
<img width="365" alt="Screenshot 2023-11-06 at 10 26 23 AM" src="https://github.com/SolaWing/xcode-build-server/assets/18671480/e3f29ed8-1974-4dd2-b994-3f59d90114ba">

What do you mean by LSP root? Should the buildServer.json be somewhere other than the root of my project directory?

buildServer.json:
<img width="1028" alt="Screenshot 2023-11-06 at 10 27 32 AM" src="https://github.com/SolaWing/xcode-build-server/assets/18671480/65fe6f73-1a91-456d-91c2-f2780b7854bc">

**Comment by SolaWing** [comment]
can you see swift LSP server log? if you config right, swift LSP server log will output xcode-build-server start.

**Comment by schwjustin** [comment]
Thanks, I got it working!
