### ISSUE TITLE
when I run Xcode-build-server, there is a problem : Requested but did not find extension point with identifier Xcode.InterfaceBuilderBuildSupport.PlatformDefinition

### ISSUE THREAD

**Issue by 0xnofoot** [SolaWing/xcode-build-server#29]
test  xcode-build-server config -scheme test -project test.xcodeproj
2023-12-16 15:26:47.072 xcodebuild[98951:6786614] Requested but did not find extension point with identifier Xcode.InterfaceBuilderBuildSupport.PlatformDefinition
find root: /Users/nofoot/Library/Developer/Xcode/DerivedData/test-fzbkifohhgxgrrgkozifedysolbm
updated buildServer.json

 test  xcodebuild -version
Xcode 15.0.1
Build version 15A507

**Comment by SolaWing** [comment]
xcode-build-server config call xcodebuild -showBuildSettings to figure out xcode build root dir. since it not affect root output, seems It just a warnninng and does not have any real issue. you can check if build server generated. and after build from xcode gui, lap should work

**Comment by 0xnofoot** [comment]
thank you for your answer very much
