### ISSUE TITLE
There is a error when I run :LspLog, I want to know if this should be a harmless error

### ISSUE THREAD

**Issue by 0xnofoot** [SolaWing/xcode-build-server#30]
[ERROR][2023-12-18 13:23:56] .../vim/lsp/rpc.lua:734	"rpc"	"/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/sourcekit-lsp"	"stderr"	"INFO:root:Xcode Build Server Startup. Waiting Request...\n"

it just tell me waiting request, is it harmless?

**Comment by SolaWing** [comment]
I don't know why your client print a ERROR. the `INFO:root:Xcode Build Server Startup. Waiting Request...\n` is just a tip that xcode-build-server already startup. it is harmless and the request log in debug level so default you are not see it. If you have any trouble, you can `export XBSDEBUG=1` or `export SOURCEKIT_LOGGING=3` to view more detail logs.

**Comment by 0xnofoot** [comment]
Thank you for your answer.
