### ISSUE TITLE
LSP doesn't come with code completions/suggestions

### ISSUE THREAD

**Issue by bengidev** [SolaWing/xcode-build-server#32]
Hello, i haven't code completions/suggestions while my LSP is successfully activate and i've generate `buildServer.json` in the root of my working directories. Here are some screenshoots for my problem:

- I want to integrate `SourceKit-LSP` with my NeoVim, and here are my configurations:
![Screenshot 2024-01-28 at 09 33 12](https://github.com/SolaWing/xcode-build-server/assets/48014755/8ff430bd-05d3-4264-98ec-c02377b41dff)

- Here are my cloned `xcode-build-server` repos:
![Screenshot 2024-01-28 at 09 34 17](https://github.com/SolaWing/xcode-build-server/assets/48014755/60367fd6-71af-4553-930a-0a9efedd6ca5)

- Here are my generated `buildServer.json`
![Screenshot 2024-01-28 at 09 35 33](https://github.com/SolaWing/xcode-build-server/assets/48014755/1cc23ea3-4a04-455c-919e-050f0911f495)

- Here are my working directories
![Screenshot 2024-01-28 at 09 36 12](https://github.com/SolaWing/xcode-build-server/assets/48014755/38ec1d4e-c2fc-4d83-ac80-7a2d205f5ec9)

- Here are my `LspLog` when i open my Swift file:
![Screenshot 2024-01-28 at 09 38 10](https://github.com/SolaWing/xcode-build-server/assets/48014755/ffa53aa3-cc6f-45c3-89cd-c799740b0402)

- I try to type `import` and Lsp doesn't give anything about suggestions/completions:
![Screenshot 2024-01-28 at 09 37 29](https://github.com/SolaWing/xcode-build-server/assets/48014755/cb5d6cf2-c430-4fb6-a1f1-aea553af4124)

So, that's my report for you. I hope i can develop iOS app outside XCode environment.
Thank you very much for your great work, mate 🍻

**Comment by SolaWing** [comment]
@bengidev Your `build_root_dir` seems incorrect.. xcode-build-server expect to read xcode build log from `<build_root_dir>/Logs/Build/` dir. this dir normally default to `~/Library/Developer/Xcode/DerivedData/XXX-hash`

can you show me your `xcodebuild -showBuildSettings -scheme Orbinews -workspace XXX | fgrep BUILD_DIR` result?

**Comment by SolaWing** [comment]
seems you change the default build dir, and the build_dir has space in path, so extract build_root failed..

**Comment by SolaWing** [comment]
I push a fix to allow space in BUILD_DIR, you can check if your LSP works?

**Comment by wojciech-kulik** [comment]
@bengidev did it help?

**Comment by SolaWing** [comment]
this time your build_root seems correct. 

I see you use -project(not workspace) as config, and your xcode is custom Xcode-15.2.app, so you should check you use same project and same xcode version as xcode-build-server config. after you build, you should see a newer log in your configed build root, see `ls -al ~/Library/Developer/Xcode/DerivedData/Tester-*/Logs/Build`, xcode-build-server get flags from it.

if you log generate correctly, you can check detail logs by export envirment: `SOURCEKIT_LOGGING=3`, you export in your terminal if you use terminal vim, or set in your vim's environment before lsp start.

**Comment by bengidev** [comment]
I'm sorry, i don't get what you suggest`so you should check you use same project and same xcode version as xcode-build-server config`. Can you explain more simpler to me?

And where am i supposed to put this `SOURCEKIT_LOGGING=3`?

**Comment by SolaWing** [comment]
1. Run xcode build, and check a newer log file generated in the build_root dir `ls -al ~/Library/Developer/Xcode/DerivedData/Tester-*/Logs/Build`
2. In vim before lsp setup, call vimscript `let $SOURCEKIT_LOGGING="3"`

**Comment by bengidev** [comment]
I try to run your number 1 suggestions, but i still don't understand your number 2 suggestions, sorry.

I try to create new project with name `NewTest`:
- This is `xcode-build-server config -scheme NewTest -project *.xcodeproj` result:
![Screenshot 2024-02-05 at 15 33 21](https://github.com/SolaWing/xcode-build-server/assets/48014755/ff85b49e-f735-42ae-ba42-759e91320cb2)

- This is `ls -al ~/Library/Developer/Xcode/DerivedData/NewTest-*/Logs/Build` result:
![Screenshot 2024-02-05 at 15 36 04](https://github.com/SolaWing/xcode-build-server/assets/48014755/167e2b35-4e19-46c5-b8e2-03cb0c62663c)

**Comment by bengidev** [comment]
- This is when i try to set the environment using `Lua`:
![Screenshot 2024-02-05 at 15 55 31](https://github.com/SolaWing/xcode-build-server/assets/48014755/9260daf0-a5d0-4448-b626-320f5958da27)

- This is when i try to re-create `xcode-build-server config -scheme NewTest -project *.xcodeproj`:
![Screenshot 2024-02-05 at 16 12 01](https://github.com/SolaWing/xcode-build-server/assets/48014755/1b5a7d06-81fe-48f5-a2d4-48c8a688fbe8)

- This is when i try to open `NewTest-domdvhi*`:
![Screenshot 2024-02-05 at 16 03 15](https://github.com/SolaWing/xcode-build-server/assets/48014755/8f4737ff-4055-4e4a-acde-e70bb0dca13f)

- This is the `LspLog` when i try to type `impo` in `ViewController.swift` file:
![Screenshot 2024-02-05 at 16 06 22](https://github.com/SolaWing/xcode-build-server/assets/48014755/b4d8c0db-20a1-4866-a3d4-0025dddd3d10)

**Comment by SolaWing** [comment]
Can you upload the LspLog as file?

**Comment by bengidev** [comment]
This is the `LspLog.txt`:
[LspLog.txt](https://drive.google.com/file/d/1cFkV3BfRA_-6mj_SH8BUd48jY3A0--BW/view?usp=share_link)

**Comment by SolaWing** [comment]
from the log seems xcode-builld-server cannot read correct flags, and return the default flags: `["/Users/beng/Downloads/NewTest/NewTest/NewTest/ViewController.swift", "-sdk", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/"]`, which is not compatible with your `Xcode-15.2.0.app` version.

when you run build, you can check if your build update logs in `ls -al /Users/beng/Library/Developer/Xcode/DerivedData/NewTest-domdvhivimfpzmckkmtgkilvyjxk/Logs/Build` dir. you also can view your build log output, see if it has same base dir as `/Users/beng/Library/Developer/Xcode/DerivedData/NewTest-domdvhivimfpzmckkmtgkilvyjxk/`

(by the way, if you has the full xcode log, you can copy it and run `pbpaste | xcode-build-server parse` at you lsp root dir, as [Readme Manual Parse Xcodebuild log](https://github.com/SolaWing/xcode-build-server?tab=readme-ov-file#manual-parse-xcodebuild-log) shows, though this way will not auto update new flags when you build)

if the build dir correct and the log is updated, you can check the log-file contains the correct logs, which may contains a cmd like `/Applications/Xcode-15.2.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -module-name <YourModule>`, if this case, you completion should work. or if xcode-build-server can't analyze the log, `xcode-build-server parse -l <Path-to.xcactivitylog> -o -` will has abnormal output, and you can upload the log file for me to debug it.

**Comment by bengidev** [comment]
- I try to run this command `xcodebuild -project *.xcodeproj -scheme NewTest -configuration Debug build | xcode-build-server parse` `pbpaste | xcode-build-server parse`, and this is the result:
![Screenshot 2024-02-06 at 12 30 36](https://github.com/SolaWing/xcode-build-server/assets/48014755/9744b148-178f-4356-801e-957d036b280f)

- I try to check if your build updating logs in `ls /Users/beng/Library/Developer/Xcode/DerivedData/NewTest-domdvhivimfpzmckkmtgkilvyjxk/Logs/Build`:
![Screenshot 2024-02-06 at 12 31 53](https://github.com/SolaWing/xcode-build-server/assets/48014755/d1920e7d-59dc-4a53-9652-83b593d448eb)

- And i try to view the build log output, and this is the result:
![Screenshot 2024-02-06 at 12 23 57](https://github.com/SolaWing/xcode-build-server/assets/48014755/89e1c0f2-4662-4b7b-bdfd-59d586ab0da1)

- I try to run this command `pbpaste | xcode-build-server parse`:
![Screenshot 2024-02-06 at 12 31 24](https://github.com/SolaWing/xcode-build-server/assets/48014755/c321509b-d8b1-46a4-8f00-a458f69658fa)

- I try to run this command `xcode-build-server debug print-xclog`:
![Screenshot 2024-02-06 at 12 34 54](https://github.com/SolaWing/xcode-build-server/assets/48014755/9e6350cb-69b9-4992-a0e0-94f196bcc908)

- And for this command, it seems not right because error happens when i run this `xcode-build-server parse -l <Path-to.xcactivitylog> -o -`

**Comment by SolaWing** [comment]
your build failed without any module flags output?

For your lsp to works, you need to:
1. Run Build, and see the build log. for simple you should try compile in xcode first, this avoid complex build params for xcodebuild and can show all logs.
2. The Xcode build should success, and the build product root should in `/Users/beng/Library/Developer/Xcode/DerivedData/NewTest-domdvhivimfpzmckkmtgkilvyjxk/`
3. check in `ls -al /Users/beng/Library/Developer/Xcode/DerivedData/NewTest-domdvhivimfpzmckkmtgkilvyjxk/Logs/Build`, LogStoreManifest.plist and a newer xcactivitylog is updated.
4. as there is log in Logs/Build, the flags should works. if not, upload this log dir for me to debug.
5. for manually parse flags, you can goto your xcode build log page, export all log to file(eg `/tmp/BuildXXX.log`), and then run cmd `xcode-build-server parse </tmp/BuildXXX.log>`. this should also works.

**Comment by bengidev** [comment]
I don't know if this works as we expected, but i've try to create new iOS App called Space News, and i've build and run previously in XCode, and when i generate `buildServer.json`, and then i try to run in NeoVim again, it seems to works. Like i try to type `import fo` and then code completions/suggestions shows up with `Foundation` and known as `Module`, not `Text` again. You can see my screenshoots down below:

- I generate the `buildServer.json`:
![Screenshot 2024-02-06 at 15 19 28](https://github.com/SolaWing/xcode-build-server/assets/48014755/37d980f3-6496-430f-a0fe-b4053dca32fd)

- I try to check the build product root:
![Screenshot 2024-02-06 at 15 22 38](https://github.com/SolaWing/xcode-build-server/assets/48014755/10c18cf3-156d-42dd-893d-83954e272e4c)

- I try to check `Logs/Build`:
![Screenshot 2024-02-06 at 15 23 14](https://github.com/SolaWing/xcode-build-server/assets/48014755/a5843e75-6153-4588-a94a-f64e2823ab86)

- And when i try to type `import fo` inside working directories:
![Screenshot 2024-02-06 at 15 19 53](https://github.com/SolaWing/xcode-build-server/assets/48014755/deab931f-55af-45f6-9f29-e6a7bc40f7a4)

- And this is when i try to type `import ui` which is correctly shows the code completions/suggestions as expected:
![Screenshot 2024-02-06 at 15 38 08](https://github.com/SolaWing/xcode-build-server/assets/48014755/2b89b76c-6d74-416f-8b67-d5143c8e05f6)

- But when i try to `import XCT`, there's no code completions/suggestions shows up:
![Screenshot 2024-02-06 at 15 41 23](https://github.com/SolaWing/xcode-build-server/assets/48014755/1399d3dd-394e-495f-811e-665b4764eb33)

You also can check my Logs directories [here](https://drive.google.com/file/d/1Z6gRzWQiFOTKCpk-xtinq58cnnSezEu5/view?usp=share_link)

**Comment by wojciech-kulik** [comment]
Maybe try also creating first a project that doesn't contain white spaces in path to make sure that it is not causing any additional problems.

**Comment by SolaWing** [comment]
Finally you compile via xcode and it works successfully. for XCTest file to work, you need to build or run test, with the same scheme to generate index and flags.

if you use same scheme to run app and test, like scheme page shows, you just need to run test by Product->Test(hotkey: `<Cmd-U>`):
<img width="203" alt="图片" src="https://github.com/SolaWing/xcode-build-server/assets/3897953/3080da4c-df6f-4a3f-b7cb-5069d20e61a5">

if you test target is in a different schema, you should ensure you config xcode-build-server with same schema and then build test.

for vim plugin works and how to bind vim build to xcode-build-server, you can ask @wojciech-kulik  for advice

**Comment by bengidev** [comment]
I try available suggestions, and this is what i get.

- I try to run the default test when i create the project:
![Screenshot 2024-02-06 at 16 28 54](https://github.com/SolaWing/xcode-build-server/assets/48014755/2e43f240-c64c-4749-8035-0825c2028050)

- I try to re-generate `buildServer.json`:
![Screenshot 2024-02-06 at 16 37 22](https://github.com/SolaWing/xcode-build-server/assets/48014755/87296a13-8395-43fb-9545-526f225eafe6)

- I try to re-open NeoVim and try to `import xct` and code completions/suggestions shows up:
![Screenshot 2024-02-06 at 16 33 21](https://github.com/SolaWing/xcode-build-server/assets/48014755/aadff2c4-0be6-44af-a0a3-4e7f4700d08c)

- I try to `import inje` and code completions/suggestions shows up:
![Screenshot 2024-02-06 at 16 38 01](https://github.com/SolaWing/xcode-build-server/assets/48014755/d6d845b5-b667-495d-a378-586df2bd5ea0)

- I try to use `Inject` in code, and code completions/suggestions shows up:
![Screenshot 2024-02-06 at 16 38 51](https://github.com/SolaWing/xcode-build-server/assets/48014755/8e39d86e-d581-4e06-8ac0-b8e825be5c5a)
![Screenshot 2024-02-06 at 16 39 05](https://github.com/SolaWing/xcode-build-server/assets/48014755/4630c6e1-6334-493b-b5e4-0960c56cd7c3)

- I try to use `gd` when the cursor above `Inject` as for Goto Definition in NeoVim:
![Screenshot 2024-02-06 at 16 39 35](https://github.com/SolaWing/xcode-build-server/assets/48014755/83b52963-e7db-40a8-ad93-2771aa57c282)

And i think finally it works really perfect. Should i close the issue?

**Comment by SolaWing** [comment]
Congratulations! If you has no more questions, feel free to close the issue

**Comment by bengidev** [comment]
I think this works very perfect, and i've try to maximize the potentials to see great articles from @wojciech-kulik again.

Thank you very much, for all of you. 
Keep your great works, and enjoy your life, mate 🍻

**Comment by ghashy** [comment]
I have been experimenting with the `Xcode-Build-Server` project using Helix editor and have noticed an interesting behavior regarding LSP suggestions. When creating Xcode projects (Xcode 15.2 (15C500b), Ventura 13.6.1) with the 'create git repo on my mac' option selected, LSP suggestions work perfectly. However, if I disable this option and create the project without a git repository, LSP suggestions do not work. I have verified that all paths are correct and have tested with other projects, but the behavior persists. Interestingly, if I create a project with git disabled and then create a repo with git init, LSP suggestions start working.

I thought this information might be helpful to others who are using the Xcode-Build-Server project and experiencing similar issues.

**Comment by SolaWing** [comment]
@ghashy seems this relative how your editor recognize lsp root.  git dir normally recognized as lsp root. you should confirm the build server dir is your lsp root dir. this should confirm by lsp logs

**Comment by wojciech-kulik** [comment]
@ghashy it's a matter of setting a proper search for your LSP. Here is what I'm doing in my nvim-lspconfig config:
```lua
    lspconfig["sourcekit"].setup({
      capabilities = capabilities,
      on_attach = on_attach,
      cmd = {
        vim.trim(vim.fn.system("xcrun -f sourcekit-lsp")),
      },
      root_dir = function(filename, _)
        local util = require("lspconfig.util")
        return util.root_pattern("buildServer.json")(filename)
          or util.root_pattern("*.xcodeproj", "*.xcworkspace")(filename)
          or util.find_git_ancestor(filename)
          or util.root_pattern("Package.swift")(filename)
      end,
    })
```
