### ISSUE TITLE
Requested but did not find extension point with identifier Xcode.InterfaceBuilderBuildSupport.PlatformDefinition

### ISSUE THREAD

**Issue by NoamEfergan** [SolaWing/xcode-build-server#37]
getting the same error for all projects. what am i missing?

**Comment by lelonco** [comment]
https://github.com/SolaWing/xcode-build-server/issues/29
I received a similar warning. It doesn't seem to be critical, just a warning

**Comment by SolaWing** [comment]
this warnning come from  `xcodebuild -showBuildSettings`. it doesn't affect any function. If you can't make lsp works, please verify you set BuildServer and build correctly from Readme

**Comment by NoamEfergan** [comment]
Will do, probably a "me" issue than . Thanks!
