### ISSUE TITLE
Can't get cross file jump to definition works

### ISSUE THREAD

**Issue by lelonco** [SolaWing/xcode-build-server#38]
I'm using VSCode with an installed Swift extension. 
I'm using this build command to build the app
```rm -r .bundle*; xcodebuild -project *.xcodeproj -sdk ${command:ios-debug.targetSdk} -destination 'generic/platform=iOS Simulator' -configuration Debug -resultBundlePath .bundle build | xcpretty && exit ${PIPESTATUS[0]} | xcode-build-server parse -a | pbpaste | xcode-build-server parse -a ```
It is built correctly.
Xcode version: 15.2
Server path in Swift extension: `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/sourcekit-lsp`

Here is my log file from sourcekit lsp:
[log.txt](https://github.com/SolaWing/xcode-build-server/files/14303355/log.txt)

In this issue, I found that message from you. But I can't figure out how to set other sdk, mb I shouldn't change it 😅
 https://github.com/SolaWing/xcode-build-server/issues/32
> from the log seems xcode-builld-server cannot read correct flags, and return the default flags: ["/Users/beng/Downloads/NewTest/NewTest/NewTest/ViewController.swift", "-sdk", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/"], which is not compatible with your Xcode-15.2.0.app version.

buildServer.json looks like that
![Screenshot 2024-02-16 at 01 21 11](https://github.com/SolaWing/xcode-build-server/assets/32571276/a324b53a-39d6-4bee-bb97-8784ad3ffdb3)

**Comment by SolaWing** [comment]
xcode-build-server parse should use raw xcode build log, this can be get by `xcodebuild build` command or export from Xcode Log UI.  It can't work after filtered by xcpretty. also notice increment build from xcodebuild, not contains all logs. so first parse from xcodebuild should be a clean build.(Xcode Log UI has all logs, so don't have to clean build)

**Comment by lelonco** [comment]
Thank you for fast response. 
I removed xcpretty, and now my command is: 
`rm -r .compile*; rm -r .bundle*; xcodebuild -project *.xcodeproj -sdk ${command:ios-debug.targetSdk} -destination 'generic/platform=iOS Simulator' -configuration Debug -resultBundlePath .bundle build | pbpaste | xcode-build-server parse -a`
But now I can't get the build log. I'm also trying to use  `exit ${PIPESTATUS[0]}` from xcpretty command, but it didn't help
![Uploading Screenshot 2024-02-16 at 12.04.21.png…]()

> also notice increment build from xcodebuild, not contains all logs. so first parse from xcodebuild should be a clean build.(Xcode Log UI has all logs, so don't have to clean build)
I make a clean build folder using Xcode. But it still not working

**Comment by SolaWing** [comment]
pbpaste is used if you manual copy log from terminal or copy. if you use xcodebuild, the command should be: `xcodebuild <param> clean build | xcode-build-server parse -a`. xcode build server only accept output from xcodebuild. if you run xcodebuild without xcode-build-server, you will see swiftc compile command in the output. that is the flags xcode-build-server get from

**Comment by lelonco** [comment]
Thank you for your help. It works now
If I want to see the xcpretty log I need to specify xclog file path?

**Comment by SolaWing** [comment]
if you want to see xcpretty output，you should reuse your log output. you tee your log output to a file, then reuse the file for parse. eg
`xcodebuild <param> clean build | tee /tmp/xcodebuild.log | xcpretty; xcode-build-server parse -a /tmp/xcodebuild.log

**Comment by lelonco** [comment]
should I make a clean build every time?

**Comment by SolaWing** [comment]
> should I make a clean build every time?

no，only first time. `xcode-build-server parse -a` will ensure merge newest logs with old logs

**Comment by lelonco** [comment]
thank you for detailed response
