### ISSUE TITLE
xcode-build-server has been added to MacPorts

### ISSUE THREAD

**Issue by woolsweater** [SolaWing/xcode-build-server#41]
Thank you so much for making this tool! It has been working perfectly for nearly a year now and making my workday so much easier! 🌟

I wanted to let you know that I have added `xcode-build-server` to MacPorts: https://github.com/macports/macports-ports/pull/22707 So this can also be included as an installation method in the README.

(If you'd like I can open up a PR myself to update the README.)

**Comment by SolaWing** [comment]
Thank you for help! I'm not familiar with macports, if I push a new release version, how can I update the macports install?

**Comment by woolsweater** [comment]
It requires a small manual update to the MacPorts "Portfile" that describes the package. The version number and the checksums need to be changed. But you don't have to worry about it. I act as the maintainer of the Portfile, and any other MacPorts user can also submit an update.

**Comment by SolaWing** [comment]
@woolsweater I have added install to Readme. is it OK?

```
or install from [Macports](https://github.com/macports/macports-ports/blob/master/devel/xcode-build-server/Portfile):

sudo port install xcode-build-server
```

**Comment by woolsweater** [comment]
Looks great! You probably don't need the link to the Portfile, but it doesn't hurt either.
