### ISSUE TITLE
buildServer.json is not updated if the path to xcode build server is changed

### ISSUE THREAD

**Issue by fireplusteam** [SolaWing/xcode-build-server#42]
Hi, just noticed the following issue (copied xcode-build-server to different locations and ran)
1. run "path_1/xcode-build-server" config -scheme "SOME_SCHEME" -workspace "some_workspace.xcworkspace"
2. buildServer.json is generated with
   ```json 
    "argv": [
		"path1/xcode-build-server"
	]
```
3. run "path_2/xcode-build-server" config -scheme "SOME_SCHEME" -workspace "some_workspace.xcworkspace"
 buildServer.json still has 
    ```json 
    "argv": [
		"path1/xcode-build-server"
	]
```

Expected is:
   ```json 
    "argv": [
		"path2/xcode-build-server"
	]
```

**Comment by SolaWing** [comment]
newest head already fix this problem. though haven’t a new release version
