### ISSUE TITLE
Support for Xcode 15.3

### ISSUE THREAD

**Issue by wojciech-kulik** [SolaWing/xcode-build-server#44]
It looks like `xcode-build-server` doesn't work with Xcode 15.3:

```xcode-build-server config -project MyProj.xcodeproj -scheme MyProj
2024-03-06 01:55:54.640 xcodebuild[96558:26618928]  DVTPlugInQuery: Requested but did not find extension point with identifier 'Xcode.InterfaceBuilderBuildSupport.PlatformDefinition'. This is programmer error; code should only request extension points that are defined by itself or its dependencies.
find root: /Users/wkulik/Library/Developer/Xcode/DerivedData/MyProj-adasdasdadasd
updated buildServer.json
```

```
[START][2024-03-06 01:58:28] LSP logging initiated
[ERROR][2024-03-06 01:58:28] .../vim/lsp/rpc.lua:784	"rpc"	"/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/sourcekit-lsp"	"stderr"	"INFO:root:Xcode Build Server Startup. Waiting Request...\n"
```

**Comment by SolaWing** [comment]
can you give the detail error with SOURCEKIT_LOGGING=3?

**Comment by wojciech-kulik** [comment]
Could you release the new version to Homebrew?

**Comment by SolaWing** [comment]
@wojciech-kulik newest head is ok? is the same reason as #40?

**Comment by wojciech-kulik** [comment]
Here are logs:
[logs.txt](https://github.com/SolaWing/xcode-build-server/files/14509070/logs.txt)

> if newest head is ok I will release a new formal release

I'm currently using Homebrew release. However, I think we can wait with release till Xcode 15.3 support is fixed.

**Comment by SolaWing** [comment]
Maybe xcode 15.3 build update flags and need to rebuild and refresh flags?

**Comment by wojciech-kulik** [comment]
Maybe, I think it started working after a clean build from Xcode. You can release to Homebrew what you already have. I don't experience this issue anymore.

**Comment by SolaWing** [comment]
I have push a new release https://github.com/SolaWing/xcode-build-server/releases/tag/v1.0.1 to master. I will update brew version soon
