### ISSUE TITLE
Question: is LSP restart required after updating `buildServer.json`?

### ISSUE THREAD

**Issue by wojciech-kulik** [SolaWing/xcode-build-server#46]
I wonder if it's required to restart LSP after `xcode-build-server config` is called? In my case, user may want to change the scheme, it will require updating the config, but is it necessary to also restart LSP after that?

**Comment by SolaWing** [comment]
Under normal circumstances, you do not need to restart the LSP. xcode-build-server will monitor changes in the buildServer.json and flags files and notify the LSP of the updated flags. However, if you switch to a scheme that has not been compiled before, you need to trigger a compilation and update flags.
