### ISSUE TITLE
Parse log with UnicodeDecodeError

### ISSUE THREAD

**Issue by TMTBO** [SolaWing/xcode-build-server#47]
I parse my xcodebuild log with the command below and got UnicodeDecodeError. Any suggestion for this? 

` xcode-build-server parse .nvim/xcodebuild/original_logs.log -o .nvim/xcodebuild/.compile`

![image](https://github.com/SolaWing/xcode-build-server/assets/2801001/811c6d5a-b935-46d2-b6de-19b95f694344)

my xcodebuild log file
[original_logs.log](https://github.com/SolaWing/xcode-build-server/files/14583922/original_logs.log)

**Comment by SolaWing** [comment]
Strange, I successfully ran same command..

**Comment by TMTBO** [comment]
![image](https://github.com/SolaWing/xcode-build-server/assets/2801001/731f111d-2b26-4f06-b3f0-4a16b35aded1)
Some unexpected chars appear in the log file and I will taken a look at that. Thanks for you answer.
