### ISSUE TITLE
Description of the process

### ISSUE THREAD

**Issue by wojciech-kulik** [SolaWing/xcode-build-server#51]
Hi!

I'm very curious how it all works. In issues, I constantly see the keyword `flags`, but I don't understand what they are for and how they are used or produced (besides that they come from build logs).

It would be really nice if you could provide in README or in another document a short description of the process. I guess it could help others to contribute and better understand the tool and its limitations.

**Comment by SolaWing** [comment]
Oh, the flags’s full name is compile flags, it’s coming from clang and I keep call it the same way. see https://clangd.llvm.org/config#compileflags

it’s actually the same things as args pass to clang or swiftc, to make the compile works.

eg: -F flag to tell how to find the frameworks.

xcode-build-server actually get the compile command from logs, and feed it to lsp, with some compatibility issue handled(eg: lsp doesn’t recognize flags read from file by @file, xcode-build-server expand it)

**Comment by wojciech-kulik** [comment]
Thank you for the great explanation!

I'm checking build logs and I see something like:
```
{
  "kind": "began",
  "name": "compile",
  "command": "\/Applications\/Xcode.app\/Contents\/Developer\/Toolchains\/XcodeDefault.xctoolchain\/usr\/bin\/swift-frontend -emit-module ....",
  "command_executable": "\/Applications\/Xcode.app\/Contents\/Developer\/Toolchains\/XcodeDefault.xctoolchain\/usr\/bin\/swift-frontend",
  "command_arguments": [
    "-emit-module",
    "-experimental-skip-non-inlinable-function-bodies-without-types",
    ...
```

Do you get flags form here?

**Comment by SolaWing** [comment]
similar somethings. but use swiftc command, not swift-frontend
