### ISSUE TITLE
Does this project work with Cocoapods?

### ISSUE THREAD

**Issue by DanielEdrisian** [SolaWing/xcode-build-server#53]
I have an app that uses pods, and for some reason it isn't able to detect pod libraries (everything else like foundation works). Is it a workspace thing? Is there a specific setup I need to do to run with cocoapods?

Sorry if I'm new!

**Comment by SolaWing** [comment]
yes, it support cocoapods. Did you setup buildServer.json as Readme says? What version your xcode-build-server is?
