### ISSUE TITLE
Document setting correct sourcekit-lsp path

### ISSUE THREAD

**Issue by jwhitley** [SolaWing/xcode-build-server#58]
I ran into the same problem as in #45, and some related XCode 15.3+ issues. At least on my system `/usr/bin/sourcekit-lsp` simply does not work as expected, emitting the standard library related error message in those threads. @wojciech-kulik's config fix below worked great for using the correct LSP binary.  That plus clearing out old DerviedData dirs and rebuilding my project got me up and running with xcode-build-server.

> Also, make sure that you are running the correct `sourcekit-lsp` by setting the following path:
```
cmd = {
  vim.trim(vim.fn.system("xcrun -f sourcekit-lsp")), -- maybe just "xcrun sourcekit-lsp" would be enough?
},
```
> in your `nvim-lspconfig`.

> Probably the problem is somewhere else, but it's worth checking the configuration first :).

_Originally posted by @wojciech-kulik in https://github.com/SolaWing/xcode-build-server/issues/45#issuecomment-1989330318_

**Comment by SolaWing** [comment]
Thank you for suggestion. add a tip in Readme, see https://github.com/SolaWing/xcode-build-server/commit/38a0eebded43342f950657267ce1f1deca9e4eaf
