### ISSUE TITLE
Xcode 16 beta support

### ISSUE THREAD

**Issue by fireplusteam** [SolaWing/xcode-build-server#59]
I installed Xcode 16 beta 2 and autocompletion doesn't work, vs code extension says that compile_flags.json is not provided. 

Has anybody tested it for a new Xcode ?

**Comment by SolaWing** [comment]
what is your full log? best with detail debug logs. compile json can’t found seems clangd flags not get from bsp

**Comment by fireplusteam** [comment]
will wait next beta and try it again as I deleted the current one :)

**Comment by wojciech-kulik** [comment]
Hi, still doesn't work with latest Beta 3:

```
LSP[sourcekit][Warning] Failed to get compiler arguments for MyViewModel.swift.
Ensure the source file is part of a Swift package or has compiler arguments in compile_commands.json.
Functionality will be limited.
```

Full log:
[lsp.log](https://github.com/user-attachments/files/16325017/lsp.log)

Also for some reason it can't detect DerivedData location properly, I had to set it manually.

**Comment by humblehacker** [comment]
I've been seeing that warning for a while now, though it hasn't seemed to affect functionality. Nevertheless it's annoying, so I looked into it a little deeper this morning, and the code in sourcekit-lsp where this warning is generated has been substantially changed in the latest release/6.0 branch - so much that this warning is gone from the code. I suspect this warning will go away in the next Xcode 16 beta. 

Sorry I can't speak to your derived data problem.

**Comment by SolaWing** [comment]
@wojciech-kulik your log seems no logs related to buildServer, was buildServer launched? I don't use beta version xcode, so sorry I can't debug it.

**Comment by SolaWing** [comment]
Xcode 16 was released and I ran it successfully without any problems. This is closed for now. If you have any questions, you can raise another issue.
