### ISSUE TITLE
Bazel support

### ISSUE THREAD

**Issue by ychie** [SolaWing/xcode-build-server#61]
Hey @SolaWing,

I'm struggling for a while now to make your tool work with .xcodeproj generated by [bazel](https://github.com/MobileNativeFoundation/rules_xcodeproj) and it do not seem like getting somewhere, so i decided to ask for help.

Lsp logs do not seem to be informative
![Screenshot 2024-08-07 at 12 33 07](https://github.com/user-attachments/assets/fe396785-894c-4e5e-8dc8-561f486e5411)

As i see it xcode-build-server is failing to generate compile_file because i see it in cache for standard .xcodeproj, but not for one generated by bazel, and i do not understand how to fix that.
![Screenshot 2024-08-07 at 12 39 35](https://github.com/user-attachments/assets/a03bb04d-3671-44f2-b569-ca5bcb64bff7)

I saw in the other bazel related ticket that you were asking for xcode build logs, so here is an example of one.
[Build Bazel_2024-08-07T12-24-03.txt](https://github.com/user-attachments/files/16521581/Build.Bazel_2024-08-07T12-24-03.txt)

Please feel free to ask me for any additional information.

**Comment by SolaWing** [comment]
seems you use custom swiftc to build. add --skip-validate-bin flag to your parse of config command.

**Comment by ychie** [comment]
@SolaWing it is working! But with some minor issue.

I also noticed that generated buildServer.json `build_root` value for some reason is pointing deeper into project's DerivedData directory, which does not happen when it is generated for default .xcodeproj. When i manually remove redundant part that is highlighted on the picture auto completion begin to work as expected. Maybe you know what may be causing this.
![Screenshot 2024-08-07 at 18 42 37](https://github.com/user-attachments/assets/dab8735b-a315-4986-8660-634ab08d6127)

Anyway thanks for your time! You helped me a lot!

**Comment by SolaWing** [comment]
what is your xcodebuild -showBuildSettings output? build_root get from following script:

```python
    cmd = f"""xcodebuild -showBuildSettings -workspace '{workspace}' -scheme '{scheme}' 2>/dev/null | grep "\\bBUILD_DIR =" | head -1 | awk -F" = " '{{print $2}}' | tr -d '"' """
    build_dir = subprocess.check_output(cmd, shell=True, universal_newlines=True)
    build_root = os.path.join(build_dir, "../..")
    build_root = os.path.abspath(build_root)
    print("find root:", build_root)
```

**Comment by ychie** [comment]
my output ends with /Build/Produces/Debug-iphoneos

**Comment by SolaWing** [comment]
what's your full output for `xcodebuild -showBuildSettings`? I am trying to find a path that compatible with xcode and bazel output..

**Comment by ychie** [comment]
[build_settings.txt](https://github.com/user-attachments/files/16542032/build_settings.txt)
