### ISSUE TITLE
Background indexing

### ISSUE THREAD

**Issue by yaroslavyaroslav** [SolaWing/xcode-build-server#67]
Folks from Apple just closed LSP support for Xcode project implicitly referencing to this project. https://github.com/swiftlang/sourcekit-lsp/issues/730#issuecomment-2394722212

So in the link that they provides to BSP mentioned background indexing capability. I have little knowledge to figure out whether it's just a placeholder or smth useful, so just raising it here. https://github.com/swiftlang/sourcekit-lsp/blob/main/Contributor%20Documentation/Implementing%20a%20BSP%20server.md

**Comment by SolaWing** [comment]
Thank you for your feedback. LSP seems to open up more command and events, and needs to provide the relationship between target and source. I need some time to understand how they work as a whole, but the overall idea of ​​​​implementing Background indexing should still be consistent with #52.

**Comment by yaroslavyaroslav** [comment]
Yeah, missed that one, so I believe this one can be closed now
