### ISSUE TITLE
Not all projects have workspace inside

### ISSUE THREAD

**Issue by fireplusteam** [SolaWing/xcode-build-server#69]
Here is the example of project from TCA which doesn't have workspace in SpeechRecognition.xcodeproj
[SpeechRecognition.zip](https://github.com/user-attachments/files/17354442/SpeechRecognition.zip)

but command 
```cmd = f"""xcodebuild -showBuildSettings -workspace '{workspace}' -scheme '{scheme}' 2>/dev/null | grep "\\bSYMROOT =" | head -1 | awk -F" = " '{{print $2}}' | tr -d '"' """```

expects always workspace to be presented resulted that buildSever.json wronly generated for such projects and autocomplete is not working at all

**Comment by SolaWing** [comment]
<img width="256" alt="image" src="https://github.com/user-attachments/assets/aa3abf5d-9f9d-4bd9-a6c9-fa87a005f806">

I open it with xcode, and the project.xcworkspace is generated. 

so if you build with xcode, the project.xcworkspace should always exists... if you only build from terminal, you may use parse to manually update .compile flags?

**Comment by fireplusteam** [comment]
But if you don't open it, the workspace is not there and xcodebuild server is not producing right buildServer.json. 
With my extension I don't want to open Xcode to build it first :)

**Comment by SolaWing** [comment]
I have tested with a project without workspace, the xcodebuild wont't generate Logs, even with -resultBundlePath. 

so `xcode-build-server config XXX` is bind to the build generated Logs file, and seems not compatible with pure project.
for pure project, try use [manual parse](https://github.com/SolaWing/xcode-build-server?tab=readme-ov-file#manual-parse-xcodebuild-log) way as `xcodebuild -project XXX build | xcode-build-server parse `

**Comment by fireplusteam** [comment]
weird behavior of xcodebuild tool, that in some cases we need to open Xcode to make it to work. Thanks for your investigation. 
Probably we can close this issue as it's not resolvable at this stage

**Comment by SolaWing** [comment]
I tested you only need to make a dir `project.xcworkspace` in xcodeproj dir. and all workspace related command of xcodebuild is ok. so you don't really need to open xcode
