### ISSUE TITLE
Nothing but just wanna say that you are my savior

### ISSUE THREAD

**Issue by suckerSlayer** [SolaWing/xcode-build-server#8]
thanks!

**Comment by tami5** [comment]
Me too thanks sooooooo much @SolaWing, was going to give up on the whole vim/swift development 😆

**Comment by hatunike** [comment]
Also accept my love! Vim on an iOS project, was annoyed at missing lsp. Now i'm happy. Thanks.

**Comment by tami5** [comment]
> Also accept my love! Vim on an iOS project, was annoyed at missing lsp. Now i'm happy. Thanks.

checkout https://github.com/tami5/xbase

**Comment by diegodorado** [comment]
You're a genius! you saved my day!
